### ISSUE TITLE
Package Update fails inside the buildspec install phase

### ISSUE THREAD

**Issue by cadm-markus-brune** [aws-solutions/aws-control-tower-customizations#147] opened 2023-01-27 10:37 UTC
**Describe the bug**
The build steps throw these errors:
  | 2023-01-25T07:04:35.642+01:00 | [Container] 2023/01/25 06:04:31 Running command apt-get -q update 1> /dev/null
-- | -- | --
  | 2023-01-25T07:04:41.796+01:00 | W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/google-chrome.list:3 and /etc/apt/sources.list.d/google.list:1
  | 2023-01-25T07:04:41.796+01:00 | W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/google-chrome.list:3 and /etc/apt/sources.list.d/google.list:1
  | 2023-01-25T07:04:41.796+01:00 | W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
  | 2023-01-25T07:04:41.796+01:00 | E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
  | 2023-01-25T07:04:41.796+01:00 | W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/google-chrome.list:3 and /etc/apt/sources.list.d/google.list:1
  | 2023-01-25T07:04:41.796+01:00 | W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/google-chrome.list:3 and /etc/apt/sources.list.d/google.list:1

**To Reproduce**
Each time the pipeline runs.

**Expected behavior**
The package update should run without problems

**Solution**
Added the following line
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
before this line      
      - apt-get -q update 1> /dev/null

**Please complete the following information about the solution:**
- [ ] Version: v2.5.2
- [ ] Region: eu-central-1
- [ ] Was the solution modified from the version published on this repository? no
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? no, because it has nothing to do with it
- [ ] Were there any errors in the CloudWatch Logs? pasted about

**Comment by balltrev** [comment] 2023-01-30 18:20
I believe this issue is a duplicate of https://github.com/aws-solutions/aws-control-tower-customizations/issues/144 and has been resolved by the AWS CodeBuild team.

**Closed by balltrev** 2023-01-30 18:20 UTC
Labels: bug
