### ISSUE TITLE
Template format error: YAML not well-formed. (line 120, column 13)

### ISSUE THREAD

**Issue by adenkang** [aws-solutions/aws-control-tower-customizations#103] opened 2022-04-20 07:09 UTC
**Describe the bug**

When I update CFCT template using custom-control-tower-initiation.template under aws-control-tower-customizations-2.2.0/deployment, There is template format error: YAML not well-formed. (line 120, column 13)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Please complete the following information about the solution:**
- [v2.2.0] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0089) - customizations-for-aws-control-tower Solution. Version: v1.0.0_". You can also find the version from [releases](https://github.com/aws-solutions/aws-control-tower-customizations/releases)

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
![스크린샷 2022-04-20 오후 4 09 09](https://user-images.githubusercontent.com/735628/164170964-4119485e-b9ed-4a30-a9f0-3051564f587e.png)

**Comment by snebhu3** [comment] 2022-04-21 02:03
Can you retry using https://github.com/aws-solutions/aws-control-tower-customizations/blob/main/customizations-for-aws-control-tower.template

**Comment by jo-koe** [comment] 2022-04-21 06:49
Same error occurs with latest template:

`An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: YAML not well-formed. (line 26, column 66)`

**Comment by balltrev** [comment] 2022-04-21 17:23
Hey @jo-koe can you confirm you're using the [latest template published from the v2.3.0 release](https://github.com/aws-solutions/aws-control-tower-customizations/blob/main/customizations-for-aws-control-tower.template)? We're not able to reproduce the error you're experiencing.

**Comment by jo-koe** [comment] 2022-04-22 05:42
Hey @balltrev I was using the latest template, but didn't download it from GitHub in raw format 🤦‍♂️. Works now - Thanks!

**Comment by balltrev** [comment] 2022-04-26 17:36
Hey @adenkang feel free to update us with any further information here, in the mean time I'm going to close this issue, thanks!

**Closed by balltrev** 2022-04-26 17:36 UTC
Labels: bug
