### ISSUE TITLE
Stackset isn't deleted when we remove the reference from manifest.yaml

### ISSUE THREAD

**Issue by rmsilva1973** [aws-solutions/aws-control-tower-customizations#91] opened 2022-02-09 14:16 UTC
**Describe the bug**
When we remove a stackset entirely from the manifest.yaml it doesn't get deleted by the pipeline

**To Reproduce**
- Create a stackset on manifest.yaml, target it to one or more accounts/OUs and commit the code to start the pipeline
- Confirm the stackset has been deployed
- Remove the stackset entry entirely from the manifest.yaml and commit the code to start the pipeline
- Confirm that the stackset hasn't been deleted

(On our environment, we have several stacksets on manifest.yaml. Perhaps creating at least two different stacksets and removing one of them is a more certain way to reproduce)

**Expected behavior**
Stackset should be deleted (and stack instances removed from all OUs/accounts) when it's entry is removed from manifest.yaml

**Please complete the following information about the solution:**
- [x] Version: 2.1.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0089) - customizations-for-aws-control-tower Solution. Version: v1.0.0_". You can also find the version from [releases](https://github.com/aws-solutions/aws-control-tower-customizations/releases)

- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository? Nope
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? Nope

**Comment by rakshb** [comment] 2022-02-21 20:54
@rmsilva1973 Thanks for reporting this. We have added this to our backlog.

**Comment by word** [comment] 2022-03-09 19:12
Looks like a duplicate of https://github.com/aws-solutions/aws-control-tower-customizations/issues/24

**Comment by gabrielbac** [comment] 2022-08-30 20:07
This is now supported in version 2.5.0

**Comment by stumins** [comment] 2023-11-07 19:41
Supported as of [v2.5.0](https://github.com/aws-solutions/aws-control-tower-customizations/releases/tag/v2.5.0) when the `enable_stack_set_deletion` flag is set to `true`

**Closed by stumins** 2023-11-07 19:41 UTC
Labels: bug
